version: '3.8'

services:
  waterwizard-server:
    build:
      context: .
      dockerfile: ./src/WaterWizard.Server/Dockerfile
    ports:
      - "7777:7777"
    environment:
      - PUBLIC_ADDRESS=${SERVER_IP}