name: .NET Tests

on:
  push:
    branches: [ main, develop, dev]
  pull_request:
    branches: [ main, develop, dev]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore WaterWizards.sln

      - name: Build
        run: dotnet build WaterWizards.sln --no-restore --configuration Release

      - name: Run tests
        run: dotnet test WaterWizards.sln --no-build --configuration Release --logger "trx;LogFileName=test-results.trx" 